USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS wh_dev WITH WAREHOUSE_SIZE='XSMALL'
  AUTO_SUSPEND=60 AUTO_RESUME=TRUE INITIALLY_SUSPENDED=TRUE;

CREATE DATABASE IF NOT EXISTS dataco;
CREATE SCHEMA IF NOT EXISTS dataco.raw;
CREATE SCHEMA IF NOT EXISTS dataco.staging;
CREATE SCHEMA IF NOT EXISTS dataco.marts;
