select
    order_item_id as order_item_key,
    order_id,
    customer_id as customer_key,
    product_card_id as product_key,
    md5(concat_ws('|', order_city, order_state, order_country, order_region, market)) as geography_key,
    md5(shipping_mode) as shipping_mode_key,
    to_number(to_char(order_date_dateorders, 'YYYYMMDD')) as date_key,
    to_number(to_char(shipping_date_dateorders, 'YYYYMMDD')) as shipping_date_key,
    type as payment_type,
    order_status,
    delivery_status,
    order_item_quantity as quantity,
    order_item_product_price as unit_price,
    sales,
    order_item_discount as discount,
    order_item_discount_rate as discount_rate,
    order_item_total,
    order_profit_per_order as profit,
    order_item_profit_ratio as profit_ratio,
    days_for_shipping_real as shipping_days_real,
    days_for_shipment_scheduled as shipping_days_scheduled,
    days_for_shipping_real - days_for_shipment_scheduled as shipping_delay_days,
    (delivery_status = 'Late delivery') as is_late
from {{ ref('stg_supply_chain_orders') }}
